# services:
#   web:
#     image: nginx:latest
#     volumes:
#       - ./:/var/www
#       - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     ports:
#       - "80:80"
#     environment:
#       - NGINX_HOST=localhost
#     networks:
#       - laravel-development
#     depends_on:
#       php-fpm:
#         condition: service_started

#   php-fpm:
#     build:
#       context: .
#       dockerfile: ./docker/common/php-fpm/Dockerfile
#       target: development
#       args:
#         UID: ${UID:-1000}
#         GID: ${GID:-1000}
#         XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
#         XDEBUG_MODE: develop,coverage,debug,profile
#         XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
#         XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
#         XDEBUG_LOG: /dev/stdout
#         XDEBUG_LOG_LEVEL: 0
#     env_file:
#       - .env
#     user: "${UID:-1000}:${GID:-1000}"
#     volumes:
#       - ./:/var/www
#     networks:
#       - laravel-development
#     depends_on:
#       mysql:
#         condition: service_started

#   workspace:
#     build:
#       context: .
#       dockerfile: ./docker/development/workspace/Dockerfile
#       args:
#         UID: ${UID:-1000}
#         GID: ${GID:-1000}
#         XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
#         XDEBUG_MODE: develop,coverage,debug,profile
#         XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
#         XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
#         XDEBUG_LOG: /dev/stdout
#         XDEBUG_LOG_LEVEL: 0
#     tty: true
#     stdin_open: true
#     env_file:
#       - .env
#     volumes:
#       - ./:/var/www
#     networks:
#       - laravel-development

#   mysql:
#     image: mysql:8
#     ports:
#       - "${MYSQL_PORT:-3306}:3306"
#     environment:
#       - MYSQL_DATABASE=app
#       - MYSQL_USER=laravel
#       - MYSQL_PASSWORD=secret
#       - MYSQL_ROOT_PASSWORD=secret
#     volumes:
#       - mysql-data-development:/var/lib/mysql
#     networks:
#       - laravel-development

#   mysql:
#     image: mysql:latest
#     container_name: mysql-master
#     command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
#     environment:
#       - MYSQL_DATABASE=app
#       - MYSQL_USER=laravel
#       - MYSQL_PASSWORD=secret
#       - MYSQL_ROOT_PASSWORD=secret
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data-first:/var/lib/mysql
#     networks:
#       - laravel-development

#   mysql_second:
#     image: mysql:latest
#     container_name: mysql-slave
#     depends_on:
#       - mysql
#     command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
#     environment:
#       MYSQL_DATABASE: mysql_second
#       MYSQL_USER: laravel
#       MYSQL_PASSWORD: secret
#       MYSQL_ROOT_PASSWORD: secret
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql-data-second:/var/lib/mysql
#     networks:
#       - laravel-development
#   redis:
#     image: redis:alpine
#     networks:
#       - laravel-development

# networks:
#   laravel-development:

# volumes:
#   mysql-data-first:
#   mysql-data-second:

services:
  web:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - laravel-development
    depends_on:
      php-fpm:
        condition: service_started

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    env_file:
      - .env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www
    networks:
      - laravel-development
    depends_on:
      mysql:
        condition: service_started

  workspace:
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - laravel-development

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql-data-development:/var/lib/mysql
    networks:
      - laravel-development
  mysql-master:
    image: mysql:latest
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-master:/var/lib/mysql
    networks:
      - laravel-development

  mysql-slave:
    image: mysql:latest
    depends_on:
      - mysql-master
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment:
      - MYSQL_DATABASE=app_slave
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-slave:/var/lib/mysql
    networks:
      - laravel-development

  redis:
    image: redis:alpine
    networks:
      - laravel-development

networks:
  laravel-development:

volumes:
  mysql-data-development:
  # mysql-data-master:
  # mysql-data-slave:
